// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

class Page {
  final String path;
  final PageMetadata metadata;
  final String content;

  const Page({
    required this.path,
    required this.metadata,
    required this.content,
  });

  @override
  int get hashCode => path.hashCode ^ metadata.hashCode ^ content.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Page &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          metadata == other.metadata &&
          content == other.content;
}

class PageMetadata {
  final String title;
  final List<String> tags;
  final PlatformInt64? createdAt;
  final PlatformInt64? updatedAt;

  const PageMetadata({
    required this.title,
    required this.tags,
    this.createdAt,
    this.updatedAt,
  });

  @override
  int get hashCode =>
      title.hashCode ^ tags.hashCode ^ createdAt.hashCode ^ updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PageMetadata &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          tags == other.tags &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

class TextAttributes {
  final bool bold;
  final bool italic;
  final bool strikethrough;
  final bool code;
  final String? link;
  final int? header;

  const TextAttributes({
    required this.bold,
    required this.italic,
    required this.strikethrough,
    required this.code,
    this.link,
    this.header,
  });

  static Future<TextAttributes> default_() =>
      RustLib.instance.api.crateApiModelsTextAttributesDefault();

  @override
  int get hashCode =>
      bold.hashCode ^
      italic.hashCode ^
      strikethrough.hashCode ^
      code.hashCode ^
      link.hashCode ^
      header.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TextAttributes &&
          runtimeType == other.runtimeType &&
          bold == other.bold &&
          italic == other.italic &&
          strikethrough == other.strikethrough &&
          code == other.code &&
          link == other.link &&
          header == other.header;
}

class TextChunk {
  final String text;
  final TextAttributes attributes;

  const TextChunk({required this.text, required this.attributes});

  @override
  int get hashCode => text.hashCode ^ attributes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TextChunk &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          attributes == other.attributes;
}

class TreeNode {
  final String name;
  final String path;
  final bool isDirectory;
  final List<TreeNode> children;

  const TreeNode({
    required this.name,
    required this.path,
    required this.isDirectory,
    required this.children,
  });

  @override
  int get hashCode =>
      name.hashCode ^ path.hashCode ^ isDirectory.hashCode ^ children.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TreeNode &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          isDirectory == other.isDirectory &&
          children == other.children;
}

class WikiAnchor {
  final String title;
  final String version;
  final PlatformInt64? createdAt;

  const WikiAnchor({
    required this.title,
    required this.version,
    this.createdAt,
  });

  static Future<WikiAnchor> default_() =>
      RustLib.instance.api.crateApiModelsWikiAnchorDefault();

  @override
  int get hashCode => title.hashCode ^ version.hashCode ^ createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WikiAnchor &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          version == other.version &&
          createdAt == other.createdAt;
}
