// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

List<TextChunk> markdownToDelta({required String markdown}) =>
    RustLib.instance.api.crateApiParserMarkdownToDelta(markdown: markdown);

String deltaToMarkdown({required List<TextChunk> chunks}) =>
    RustLib.instance.api.crateApiParserDeltaToMarkdown(chunks: chunks);
