// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `calculate_line_col`, `check_whole_word`, `extract_rendered_text_and_map`, `utf16_offset`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SourceMapping`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

/// Initialise la base de données .crowindex pour un wiki donné
bool initSearchDb({required String wikiRoot}) =>
    RustLib.instance.api.crateApiSearchInitSearchDb(wikiRoot: wikiRoot);

/// Indexe un fichier (le lit, le parse, et le stocke dans la DB)
bool indexDocument({required String filePath, required String rawMarkdown}) =>
    RustLib.instance.api.crateApiSearchIndexDocument(
      filePath: filePath,
      rawMarkdown: rawMarkdown,
    );

/// Recherche dans la base de données
List<SearchResult> searchDocuments({
  required String query,
  required int mode,
}) => RustLib.instance.api.crateApiSearchSearchDocuments(
  query: query,
  mode: mode,
);

DbHealthStatus checkDbHealth({required String wikiRoot}) =>
    RustLib.instance.api.crateApiSearchCheckDbHealth(wikiRoot: wikiRoot);

Future<bool> rebuildIndex({required String wikiRoot}) =>
    RustLib.instance.api.crateApiSearchRebuildIndex(wikiRoot: wikiRoot);

class DbHealthStatus {
  final String status;
  final String message;

  const DbHealthStatus({required this.status, required this.message});

  @override
  int get hashCode => status.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DbHealthStatus &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          message == other.message;
}

class SearchResult {
  final String filePath;
  final BigInt rawStartOffset;
  final BigInt rawEndOffset;
  final String exactMatchText;
  final String previewText;
  final BigInt lineNumber;
  final BigInt columnNumber;
  final bool isCaseMatch;
  final bool isSyntaxClean;
  final bool isWholeWord;

  const SearchResult({
    required this.filePath,
    required this.rawStartOffset,
    required this.rawEndOffset,
    required this.exactMatchText,
    required this.previewText,
    required this.lineNumber,
    required this.columnNumber,
    required this.isCaseMatch,
    required this.isSyntaxClean,
    required this.isWholeWord,
  });

  @override
  int get hashCode =>
      filePath.hashCode ^
      rawStartOffset.hashCode ^
      rawEndOffset.hashCode ^
      exactMatchText.hashCode ^
      previewText.hashCode ^
      lineNumber.hashCode ^
      columnNumber.hashCode ^
      isCaseMatch.hashCode ^
      isSyntaxClean.hashCode ^
      isWholeWord.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchResult &&
          runtimeType == other.runtimeType &&
          filePath == other.filePath &&
          rawStartOffset == other.rawStartOffset &&
          rawEndOffset == other.rawEndOffset &&
          exactMatchText == other.exactMatchText &&
          previewText == other.previewText &&
          lineNumber == other.lineNumber &&
          columnNumber == other.columnNumber &&
          isCaseMatch == other.isCaseMatch &&
          isSyntaxClean == other.isSyntaxClean &&
          isWholeWord == other.isWholeWord;
}
