// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_settings_path`, `save_settings`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Charge les paramètres depuis le fichier de config (crée par défaut si absent)
AppSettings loadSettings() =>
    RustLib.instance.api.crateApiSettingsLoadSettings();

/// Met à jour l'index du thème
void saveTheme({required int index}) =>
    RustLib.instance.api.crateApiSettingsSaveTheme(index: index);

/// Ajoute un wiki à l'historique récent
void addRecentWiki({required String wikiPath}) =>
    RustLib.instance.api.crateApiSettingsAddRecentWiki(wikiPath: wikiPath);

class AppSettings {
  final int themeIndex;
  final List<String> recentWikis;

  const AppSettings({required this.themeIndex, required this.recentWikis});

  static Future<AppSettings> default_() =>
      RustLib.instance.api.crateApiSettingsAppSettingsDefault();

  @override
  int get hashCode => themeIndex.hashCode ^ recentWikis.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppSettings &&
          runtimeType == other.runtimeType &&
          themeIndex == other.themeIndex &&
          recentWikis == other.recentWikis;
}
