// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

/// Initialise un nouveau wiki
/// Crée un dossier `name` dans `parent_path` et y ajoute le dossier caché `.crow`
String initWiki({required String parentPath, required String name}) => RustLib
    .instance
    .api
    .crateApiSimpleInitWiki(parentPath: parentPath, name: name);
